
name: nextjs-deploy-gh-pages
description: 'Deploying your Next.js repo back to the gh-pages branch of the same repository'
branding:
  icon: 'upload-cloud'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
